# What is perfectionism?

Perfectionism is a tendency to blah blah and this and that

## Big perfectionism papers and authors

## Definitions of perfectionism

## Scales to measure perfectionism
| scale                                         | #     | Our possible indication terms |
|-----------------------------------------------|-------|-------------------------------|
| Frost Multidimensional Perfectionism Scale    |   1   | FMPS                          |
| Hewitt & Flett Multidimensional Perfectionism
  Scale                                         |   2   | MPS                           |
| Almost Perfect Scale- Revised                 |   3   | APS-R                         |
| Positive and Negative Perfectionism Scale     |   4   | PANPS                         |

## Scale citations
[1] Frost, R. O., Marten, P., Lahart, C., & Rosenblate, R. (1990). The dimensions of perfectionism. Cognitive therapy and research, 14, 449-468.
[2] Hewitt, P. L., Flett, G. L., Turnbull-Donovan, W., & Mikail, S. F. (1991). The Multidimensional Perfectionism Scale: Reliability, validity, and psychometric properties in psychiatric samples. Psychological Assessment: A Journal of Consulting and Clinical Psychology, 3(3), 464.
[3] Slaney, R. B., Mobley, M., Trippi, J., Ashby, J. S., & Johnson, D. (1996). Almost Perfect Scale—Revised. Assessment.
[4] Terry-Short, L. A., Owens, R. G., Slade, P. D., & Dewey, M. E. (1995). Positive and negative perfectionism. Personality and individual differences, 18(5), 663-668.

## Keywords from scales that could indicate perfectionism

Perfectionism is not always speken about by name. There are many terms that can be used to indicate the forms and characteristics of perfectionism. We have collected a set of concepts and terms used in various perfectionism scales in order to search for trends in our text corpus. 

| concept                                       | scale | notes                         |
|-----------------------------------------------|-------|-------------------------------|
| anxiety                                       |   3   |                               |
| concerns over mistake                         |   1   |                               |
| discrepancy                                   |   3   |                               |
| doubts about actions                          |   1   |                               |
| organization                                  |   1   |                               |
| other-oriented perfectionism                  |   2   |                               |
| parental criticism                            |   1   |                               |
| parental expectations                         |   1   |                               |
| personal standards                            |   1   |                               |
| positive perfectionism                        |   4   |                               |
| procrastination                               |   3   |                               |
| negative perfectionism                        |   4   |                               |
| relationships                                 |   3   |                               |
| self-oriented perfectionism                   |   2   |                               |
| socially prescribed perfectionism             |   2   |                               |
| standards & order                             |   3   |                               |


: Possible terms that could indicate perfectionism {.striped .hover}

# Keywords from perfectionism associations

| association                                   | reference | Our possible indication terms |
|-----------------------------------------------|-----------|-------------------------------|
| depressive symptoms                           |           | depression                    |
| anxiety                                       |           | worry                         |
| authoritarianism                              |           |                               |
| avoidant                                      |           | procrastinate                 |
| chronic fatigue                               |           | "always tired"                |
| dominance                                     |           |                               |
| external locus of control                     |           | "out of control"              |
| fear of negative evaluation                   |           |                               |
| indecisiveness                                |           | unsure                        |
| loneliness                                    |           | alone                         |
| low self-perceived social skill               |           |                               |
| low social self-esteem                        |           |                               |
| need for approval                             |           |                               |
| obsessive-compulsive symptoms                 |           | OCD                           |
| procrastination                               |           |                               |
| reactions to mistakes                         |           |                               |
| schizoid                                      |           |                               |
| sexual dysfunction                            |           | incel                         |
| social anxiety                                |           |                               |
| suicidal preoccupation                        |           | kms, "end it"                 |





: Possible terms that could be associated with perfectionism {.striped .hover}


# Why perfectionism is important to study in education research

# Why we care about online communities in education research

Online communities are a place that individuals go to vent frustrations. Specific communities can be oriented towards a particular group such as engineering students. Reddit has a community intended for engineering students (r/EngineeringStudents) that has a large backlog of student experiences in text form. Shared experiences outlined on this community can indicate the struggles engineering students have faced and we should be aware of. 

Additionally, online communities act as repositories of questions and answers that students may find if they search the internet for solutions to their problems. Knowing about trends in the answers provided to engineering students online helps educators know what students may have already tried.


